# Generated by Django 2.2.16 on 2020-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201026_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='mid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
